name: number_to_vietnamese_words
description: Convert numbers to words for easy comprehension and readability in the Vietnamese language.
version: 1.0.0
repository: https://github.com/trinhvuduc/number_to_vietnamese_words

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
